version: "2"

services:
  go-live:
    image: go-live
    restart: always
    environment:
      - MYSQL_DSN=root:Xr111900@tcp(rm-wz9p9wn6719qplwioho.mysql.rds.aliyuncs.com:3306)/livego?charset=utf8
    ports:
      - 1935:1935
      - 7001:7001
      - 8090:8090
      - 8040:8040
      - 7002:7002